### PR TITLE
New artifact net4j.derby for org.eclipse.net4j.db.derby plugin

### PR DESCRIPTION
**Pull request by sunye**
Hi Guillaume,

I needed the net4j derby plugin for a project, so I added it to your project. I hope this can help!

### CODE REVIEW

**Comment by ghillairet** [comment]
Thanks, will publish it today.

**Comment by sunye** [comment]
Thanks, Guillaume!

**Comment by ghillairet** [comment]
It has been released in version 4.7.2.

**Comment by sunye** [comment]
Thanks ! I used the same pattern to create artifacts for other eclipse products (emf-related): https://github.com/sunye/emf-maven

**Pull request merged**
